# syntax=docker/dockerfile:1

FROM node:18-alpine AS build
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps apps
COPY packages packages
COPY . .
RUN pnpm install --frozen-lockfile \
    && pnpm build \
    && mkdir -p /dist \
    && mv apps/guest/dist /dist/guest \
    && mv apps/kds/dist /dist/kds \
    && mv apps/admin/dist /dist/admin

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /dist/guest /usr/share/nginx/html/guest
COPY --from=build /dist/kds /usr/share/nginx/html/kds
COPY --from=build /dist/admin /usr/share/nginx/html/admin
