version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      POSTGRES_MASTER_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/master
      POSTGRES_TENANT_DSN_TEMPLATE: postgresql+asyncpg://tenant:tenant@postgres:5432/tenant_{tenant_id}
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      POSTGRES_MASTER_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/master
      POSTGRES_TENANT_DSN_TEMPLATE: postgresql+asyncpg://tenant:tenant@postgres:5432/tenant_{tenant_id}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
