[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
exclude = ["clickup_structure_blueprint"]

[tool.ruff.lint]
select = ["E", "F"]

[tool.isort]
profile = "black"

[tool.pip-audit]
ignore-vuln = ["GHSA-wj6h-64fc-37mp"]
