[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
exclude = ["clickup_structure_blueprint", "api/tests", "tests", "scripts"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E402", "E501"]

[tool.isort]
profile = "black"

[tool.pip-audit]
ignore-vuln = ["GHSA-wj6h-64fc-37mp"]
