api:
  image: neo-api:latest
  replicaCount: 1
  env:
    - name: DATABASE_URL
      value: postgres://user:pass@db:5432/neo
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75

worker:
  image: neo-worker:latest
  replicaCount: 1
  env:
    - name: QUEUE_URL
      value: redis://redis:6379/0
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi
  livenessProbe:
    exec:
      command: ["python", "start_app.py", "healthcheck"]
  readinessProbe:
    exec:
      command: ["python", "start_app.py", "ready"]
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

nginx:
  image: nginx:1.25
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

redis:
  host: redis.example.com
  port: 6379
