groups:
  - name: neo-default
    rules:
      - alert: APIHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.02
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API error rate
          description: More than 2% of API requests returned 5xx responses in the last 5 minutes.

      - alert: APISlow
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: API latency is high
          description: 95th percentile latency above 500ms over the last 5 minutes.

      - alert: WorkerBacklogHigh
        expr: sum(jobs_queue_depth) by (queue) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Worker queue backlog is high
          description: More than 100 pending jobs detected in a worker queue for over 5 minutes.

      - alert: DigestMissed
        expr: max by (tenant) (time() - digest_last_sent_timestamp) > 24 * 60 * 60
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Tenant digest not sent in 24h
          description: A tenant has not been sent a digest notification for over 24 hours.

      - alert: DBDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database is down
          description: PostgreSQL exporter reports the database as unreachable.

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis is down
          description: Redis exporter reports the instance as unreachable.
