version: '3.9'
services:
  api:
    build: ../api
    env_file:
      - ../.env
    ports:
      - '8000:8000'
    depends_on:
      - postgres_master
      - postgres_tenant
      - redis
      - minio
  postgres_master:
    image: postgres:15
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
    ports:
      - '5432:5432'
  postgres_tenant:
    image: postgres:15
    environment:
      POSTGRES_DB: tenant
      POSTGRES_USER: ${POSTGRES_TENANT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TENANT_PASSWORD}
    ports:
      - '5433:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
  proxy:
    image: nginx:alpine
    depends_on:
      - api
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
