name: backup-smoke

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y age postgresql-client
      - name: Run backup smoke
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL_STAGING }}
          BACKUP_PUBLIC_KEY: ${{ secrets.BACKUP_PUBLIC_KEY_STAGING }}
          BACKUP_PRIVATE_KEY: ${{ secrets.BACKUP_PRIVATE_KEY_STAGING }}
        run: |
          scripts/backup_smoke.sh
