name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/neo-api:${{ github.sha }}
      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/neo-worker:${{ github.sha }}

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" > ~/.kube/config
      - name: Deploy to staging
        run: |
          helm upgrade --install neo deploy/helm/neo \
            --namespace staging \
            --set image.tag=${{ github.sha }}
      - name: Audit env examples
        run: python scripts/env_audit.py
      - name: Preflight health
        run: curl -fsS https://staging.example.com/api/admin/preflight
      - name: Smoke and canary tests
        run: |
          python scripts/smoke_release.py
          python scripts/canary_probe.py
      - name: Accessibility scan
        run: npx pa11y-ci
      - name: Playwright smoke
        run: |
          cd e2e/playwright
          npx playwright test --project=smoke

  manual-approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Awaiting approval
        run: echo "Manual approval required to deploy to production"

  deploy-prod:
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_PROD }}" > ~/.kube/config
      - name: Blue/green rollout
        run: |
          helm upgrade --install neo deploy/helm/neo \
            --namespace prod \
            --set image.tag=${{ github.sha }} \
            --set strategy=bluegreen
      - name: Preflight health
        run: curl -fsS https://prod.example.com/api/admin/preflight
      - name: Smoke and canary tests
        run: |
          python scripts/smoke_release.py
          python scripts/canary_probe.py
      - name: Accessibility scan
        run: npx pa11y-ci
      - name: Playwright smoke
        run: |
          cd e2e/playwright
          npx playwright test --project=smoke
      - name: Rollback on failure
        if: failure()
        run: helm rollback neo
