name: Nightly DWH Parquet dump

on:
  schedule:
    - cron: '0 20 * * *' # 20:00 IST
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyarrow boto3 sqlalchemy
      - name: Export nightly dump
        env:
          DWH_DB_DSN: ${{ secrets.STAGING_URL }}
          DWH_S3_URL: ${{ secrets.DWH_S3_URL }}
          DWH_S3_KEY: ${{ secrets.DWH_S3_KEY }}
          DWH_S3_SECRET: ${{ secrets.DWH_S3_SECRET }}
          DWH_S3_BUCKET: ${{ secrets.DWH_S3_BUCKET }}
          DWH_TMP_DIR: dump
        run: |
          python - <<'PY'
          import json
          from datetime import date, timedelta
          from scripts.dwh_parquet_dump import main
          day = date.today() - timedelta(days=1)
          manifest = main(day)
          with open('dump/manifest.json', 'w') as fh:
              json.dump(manifest, fh)
          PY
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dwh-parquet
          path: |
            dump/manifest.json
            dump/*/orders.parquet
