name: Owner insights

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run weekly owner insights
        env:
          OWNER_INSIGHTS_EMAIL: owner@sandbox.example.com
        run: |
          python scripts/owner_insights.py --week_start last_mon --tenants demo
