name: Pa11y

on:
  push:
  pull_request:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: neo
          POSTGRES_PASSWORD: neo
          POSTGRES_DB: neo
        options: >-
          --health-cmd="pg_isready -U neo -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      # what the app code reads (async driver)
      POSTGRES_MASTER_URL: postgresql+asyncpg://neo:neo@localhost:5432/neo
      # what Alembic uses (sync driver)
      SYNC_DATABASE_URL: postgresql://neo:neo@localhost:5432/neo

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U neo; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python -m alembic -x db_url=$SYNC_DATABASE_URL -c api/alembic.ini upgrade head

      - name: Start API
        run: |
          python start_app.py &
          sleep 5

      - name: Run Pa11y
        run: npx pa11y-ci -c pa11y-ci.json
