name: pip-audit

on:
  push:
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip install -r api/requirements.txt
      - name: Run pip-audit
        run: pip-audit -r api/requirements.txt --strict --ignore-vuln GHSA-wj6h-64fc-37mp
