name: Python tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [sqlite, postgres]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      POSTGRES_HOST: ${{ matrix.db == 'postgres' && 'localhost' || '' }}
      POSTGRES_USER: ${{ matrix.db == 'postgres' && 'postgres' || '' }}
      POSTGRES_PASSWORD: ${{ matrix.db == 'postgres' && 'postgres' || '' }}
      POSTGRES_DB: ${{ matrix.db == 'postgres' && 'postgres' || '' }}
      POSTGRES_TENANT_DSN_TEMPLATE: ${{ matrix.db == 'postgres' && 'postgresql+asyncpg://postgres:postgres@localhost:5432/{tenant_id}' || '' }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r api/requirements.txt
          pip install pytest pytest-cov pillow
          if [ "${{ matrix.db }}" = "postgres" ]; then pip install asyncpg; fi
      - name: Run tenant migrations
        if: matrix.db == 'postgres'
        run: |
          python scripts/tenant_create_db.py --tenant demo
          python scripts/tenant_seed.py --tenant demo
      - name: Lint
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Audit environment
        run: python scripts/env_audit.py
      - name: Check i18n keys
        run: pre-commit run --hook-stage manual i18n-lint --all-files
      - name: Test
        run: pytest --cov --cov-report=term --cov-fail-under=80 -q
      - name: Save print-test PNG
        run: python scripts/save_print_test_png.py
      - name: Upload print-test PNG
        uses: actions/upload-artifact@v4
        with:
          name: print-test-${{ matrix.db }}
          path: print-test.png

