name: Python tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest
      - name: Lint
        run: |
          if grep -q "[tool.black]" pyproject.toml 2>/dev/null; then
            pip install black
            black --check . || true
          fi
          if [ -f ".flake8" ] || [ -f "setup.cfg" ] || [ -f "tox.ini" ]; then
            pip install flake8
            flake8 . || true
          fi
      - name: Test
        run: pytest -q
