name: Security

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install bandit pip-audit ruff
      - name: Run bandit
        run: bandit -r api/ --severity-level high --confidence-level high
      - name: Run pip-audit
        run: pip-audit --strict --ignore-vuln GHSA-wj6h-64fc-37mp
      - name: Run ruff
        run: ruff check api/app --select F
