name: trivy

on:
  push:
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: api
            dockerfile: Dockerfile.api
          - image: worker
            dockerfile: Dockerfile.worker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.image }} image
        run: docker build -t ${{ matrix.image }} -f ${{ matrix.dockerfile }} .
      - name: Cache Trivy database
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-${{ hashFiles('Dockerfile.api', 'Dockerfile.worker') }}
          restore-keys: |
            ${{ runner.os }}-trivy-
      - name: Scan ${{ matrix.image }} image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ matrix.image }}
          format: table
          exit-code: 1
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          cache-dir: ~/.cache/trivy

