name: ui

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: guest-dist
          path: apps/guest/dist
      - uses: actions/upload-artifact@v4
        with:
          name: kds-dist
          path: apps/kds/dist
      - uses: actions/upload-artifact@v4
        with:
          name: admin-dist
          path: apps/admin/dist
