name: zap-baseline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    env:
      STAGING_URL: ${{ secrets.STAGING_URL }}
    steps:
      - name: ZAP Baseline Scan
        if: ${{ env.STAGING_URL != '' }}
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ env.STAGING_URL }}
          cmd_options: '--allowlist /auth --allowlist /callback -r zap_report.html'
          artifact_name: zap-baseline-report
